services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - kcdbdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "${KEYCLOAK_PORT}:8080"
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:rw

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${APP_DB_PORT}/${APP_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_URL}
      APP_CORS_ALLOWED_ORIGINS: ${WEB_URL}
    ports:
      - "${BACKEND_PORT}:8080"

volumes:
  pgdata:
  kcdbdata:
