server:
  port: 8080

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/taskflow}
    username: ${SPRING_DATASOURCE_USERNAME:taskflow}
    password: ${SPRING_DATASOURCE_PASSWORD:taskflow}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8081/realms/taskflow}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}
